export const SET_MOVIES = "SET_MOVIES"
export const SELECT_MOVIE = "SELECT_MOVIE"
export const LIKE_MOVIE = "LIKE_MOVIE"
export const UNLIKE_MOVIE = "UNLIKE_MOVIE"
export const SEARCH_MOVIES = "SEARCH_MOVIES"